# DSBDA Practical – Data Wrangling II

Academic Performance Dataset preprocessing using Python.

## Step 1: Import Required Libraries

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Step 2: Create Academic Performance Dataset

In [2]:

data = {
    'Student_ID': [1, 2, 3, 4, 5, 6, 7],
    'Math_Score': [78, 85, np.nan, 95, 120, 67, 80],
    'Attendance': [90, 85, 88, np.nan, 92, 40, 89],
    'Study_Hours': [2, 3, 4, 10, 12, 1, 3]
}

df = pd.DataFrame(data)
df

   Student_ID  Math_Score  Attendance  Study_Hours
0           1        78.0        90.0            2
1           2        85.0        85.0            3
2           3         NaN        88.0            4
3           4        95.0         NaN           10
4           5       120.0        92.0           12
5           6        67.0        40.0            1
6           7        80.0        89.0            3

## Step 3: Missing Values and Inconsistencies

In [3]:

df.isnull().sum()

Student_ID     0
Math_Score     1
Attendance     1
Study_Hours    0
dtype: int64

In [6]:
df['Math_Score'] = df['Math_Score'].fillna(df['Math_Score'].mean())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].mean())
df

   Student_ID  Math_Score  Attendance  Study_Hours
0           1        78.0   90.000000            2
1           2        85.0   85.000000            3
2           3        87.5   88.000000            4
3           4        95.0   80.666667           10
4           5       120.0   92.000000           12
5           6        67.0   40.000000            1
6           7        80.0   89.000000            3

## Step 4: Outlier Detection (IQR Method)

In [5]:

Q1 = df['Math_Score'].quantile(0.25)
Q3 = df['Math_Score'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

lower, upper

(np.float64(60.625), np.float64(109.625))

In [ ]:

df['Math_Score'] = np.where(df['Math_Score'] > upper, upper, df['Math_Score'])
df

## Step 5: Data Transformation (Log Transformation)

In [ ]:

df['Study_Hours_Log'] = np.log(df['Study_Hours'] + 1)
df

## Conclusion


- Missing values handled using mean  
- Outliers treated using IQR method  
- Log transformation applied to reduce skewness